"""
tests/test_c1_inverse.py
MAP reconstruction on the C^1 spaces (femmi.c1_inverse) and the circular domain.

The inverse path is where a wrong adjoint hides: the coupled operator is NOT
symmetric (the BEM double layer is not), so the transpose solve is required, and
the gauge row makes it easy to get subtly wrong. The gradient check is therefore
the load-bearing test here, not the reconstruction quality.

Run:
    python -m pytest tests/test_c1_inverse.py -v
"""

import sys, os
import numpy as np
import pytest

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from femmi.elements import C1Space, circular_triangulation
from femmi.c1_inverse import C1MAPReconstructor, shear_selection_operators
from femmi.c1_coupling import boundary_loop


def test_circular_triangulation_is_a_well_shaped_disk():
    """Boundary vertices exactly on the circle, area converging to pi R^2, and
    no needle triangles (which would wreck the element conditioning)."""
    for nb in (12, 24, 36):
        v, t = circular_triangulation(nb, radius=2.5)
        S = C1Space(v, t, kind="argyris")
        loop = boundary_loop(S)
        assert len(loop) == nb
        assert np.abs(np.hypot(v[loop, 0], v[loop, 1]) - 2.5).max() < 1e-12

        p = v[loop]
        area = 0.5 * np.sum(p[:, 0] * np.roll(p[:, 1], -1)
                            - np.roll(p[:, 0], -1) * p[:, 1])
        assert area > 0                                  # CCW
        assert area <= np.pi * 2.5**2 + 1e-9             # inscribed polygon

        ang = []
        for tri in t:
            P = v[tri]
            for k in range(3):
                u1 = P[(k + 1) % 3] - P[k]; u2 = P[(k + 2) % 3] - P[k]
                ang.append(np.degrees(np.arccos(np.clip(
                    u1 @ u2 / (np.linalg.norm(u1) * np.linalg.norm(u2)), -1, 1))))
        assert min(ang) > 15.0


def test_shear_operator_is_a_pure_selection():
    """Argyris stores the Hessian at vertices, so S1/S2 have 2 and 1 entries per
    row -- no quadrature, no averaging over adjacent elements, no boundary ring.
    This is the operator that replaces the whole of _assemble_shear_ops."""
    v, t = circular_triangulation(12, radius=2.5)
    S = C1Space(v, t, kind="argyris")
    S1, S2 = shear_selection_operators(S)
    assert S1.shape == (S.n_vertices, S.n_dofs)
    assert S1.nnz == 2 * S.n_vertices
    assert S2.nnz == S.n_vertices

    # applied to an interpolant, they must return the exact Hessian combination
    def g(p, dx=0, dy=0):
        x, y = p[0], p[1]
        if (dx, dy) == (0, 0): return x * x - 0.5 * y * y + 0.3 * x * y
        if (dx, dy) == (1, 0): return 2 * x + 0.3 * y
        if (dx, dy) == (0, 1): return -y + 0.3 * x
        if (dx, dy) == (2, 0): return 2.0
        if (dx, dy) == (0, 2): return -1.0
        if (dx, dy) == (1, 1): return 0.3
        return 0.0

    u = S.interpolate(g)
    assert np.allclose(S1 @ u, 0.5 * (2.0 - (-1.0)), atol=1e-10)
    assert np.allclose(S2 @ u, 0.3, atol=1e-10)


def test_hct_is_rejected_for_shear_selection():
    """HCT has no Hessian vertex DOFs, so the selection is undefined; it must
    fail loudly rather than return something meaningless."""
    v, t = circular_triangulation(12, radius=2.5)
    S = C1Space(v, t, kind="hct")
    with pytest.raises(ValueError, match="Hessian vertex DOFs"):
        shear_selection_operators(S)


def test_adjoint_gradient_matches_finite_differences():
    """The load-bearing test. A^T is needed because the coupled operator is not
    symmetric, and the gauge row is easy to mishandle -- either mistake shows up
    here and nowhere else."""
    v, t = circular_triangulation(12, radius=2.5)
    S = C1Space(v, t, kind="argyris")
    rec = C1MAPReconstructor(S, lam=1e-2, wiener_length=1.0)

    rng = np.random.default_rng(0)
    g1 = rng.normal(0, 0.1, S.n_vertices)
    g2 = rng.normal(0, 0.1, S.n_vertices)
    k0 = rng.normal(0, 0.05, S.n_dofs)
    _, grad = rec._obj_grad(k0, g1, g2)

    eps = 1e-6
    for j in rng.choice(S.n_dofs, 6, replace=False):
        kp = k0.copy(); kp[j] += eps
        km = k0.copy(); km[j] -= eps
        fd = (rec._obj_grad(kp, g1, g2)[0] - rec._obj_grad(km, g1, g2)[0]) / (2 * eps)
        assert abs(grad[j] - fd) / (abs(fd) + 1e-12) < 1e-4


def test_reconstruction_recovers_a_self_consistent_field():
    """Sanity of the loop as a whole: data generated by the C^1 forward must be
    invertible back to something close. This is an inverse crime by construction
    and only checks the machinery -- scoring happens against femmi.truth."""
    v, t = circular_triangulation(18, radius=2.5)
    S = C1Space(v, t, kind="argyris")
    rec = C1MAPReconstructor(S, lam=1e-4, wiener_length=0.5, maxiter=400)

    kfun = lambda P: np.exp(-(P[:, 0]**2 + P[:, 1]**2) / (2 * 0.6**2))
    g1, g2 = rec.synthesise_data(kfun, noise_std=0.0)
    k, _ = rec.reconstruct(g1, g2)

    kv = rec.kappa_at_vertices(k)
    truth = kfun(v)
    inner = np.hypot(v[:, 0], v[:, 1]) < 1.5
    dm = lambda a: a - a.mean()
    rel = (np.linalg.norm(dm(kv[inner]) - dm(truth[inner]))
           / np.linalg.norm(dm(truth[inner])))
    assert rel < 0.5


if __name__ == "__main__":
    import subprocess
    sys.exit(subprocess.call([sys.executable, "-m", "pytest", __file__, "-v"]))
