"""Regenerate tables/figures from raw held-out results; never refit on test data."""
import argparse,json,sys
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[2]))
import numpy as np
from femmi.calibration import write_json
from femmi.density import average_over_seeds,paired_comparison

METHODS=['p3','argyris','hct','ks']

def report(root,out,update_math=False):
    root=Path(root);out=Path(out);out.mkdir(parents=True,exist_ok=True)
    configs=json.loads((root.parent/'configs.json').read_text())
    allrows=[];calibrations={};audit=[]
    for config in configs:
        name=config['name'];d=root/name
        cal=json.loads((d/'calibration.json').read_text());rows=json.loads((d/'evaluation.json').read_text())
        expected={(m,s) for m in METHODS for s in config['evaluation_seeds']}
        if {(r['method'],r['seed']) for r in rows}!=expected or len(rows)!=len(expected):
            raise ValueError('incomplete or duplicate evaluation: '+name)
        if set(cal['calibrations'])!=set(METHODS):raise ValueError('incomplete calibration: '+name)
        for m in METHODS:
            r=cal['calibrations'][m]
            audit.append(dict(scenario=name,method=m,candidates=len(r['candidates']),
                failed_candidates=sum('error' in x for x in r['candidates']),
                boundary_unresolved=r['boundary_unresolved'],
                failed_evaluations=sum(x['method']==m and 'error' in x for x in rows)))
        calibrations[name]=cal;allrows.extend(rows)
    avg=average_over_seeds(allrows);pairs=[]
    for i,m in enumerate(METHODS):
        for other in METHODS[i+1:]:
            pairs += [dict(method_a=m,method_b=other,**r) for r in paired_comparison(allrows,m,other)]
    write_json(out/'raw_evaluation.json',allrows)
    write_json(out/'means.json',avg);write_json(out/'paired.json',pairs);write_json(out/'audit.json',audit)
    lines=['# Held-out calibrated comparisons','',
        'Generated by `examples/paper/report_calibration.py`. Calibration seeds 100–102; evaluation seeds 0–5. '
        'All four methods receive identical selected positions, both shear-noise components, and weights. '
        'The target is unweighted galaxy-position, DC-removed relative L2 on truth κ<1. '
        'Means ± standard errors describe six catalogues; they are not confidence bounds on universal method performance.','',
        'The former large Argyris density advantage is not supported by this corrected comparison. '
        'The FEM arms are close; Argyris has a small paired advantage over P3 at baseline densities 20 and 30. '
        'KS has lower mean error in the high-noise and masked examples, with uncertainty retained in the paired data.','',
        '## Density baseline','',
        'Centred NFW, mass 2e14, concentration 4, radius 3 arcmin, independent shear noise 0.05 per component. '
        'These source counts do not imply DES/Euclid-level performance at their actual shape noise.','',
        '| Count density / arcmin² | P3 | Argyris | HCT | KS |',
        '|---:|---:|---:|---:|---:|']
    for n in (5,10,20,30):
        rs={r['method']:r for r in avg if r['scenario']==f'density-{n}'}
        lines.append('| '+str(n)+' | '+' | '.join(f"{rs[m]['shape_l2']:.4f} ± {rs[m]['shape_l2_std']:.4f}" for m in METHODS)+' |')
    lines += ['', '## Frozen settings', '', '| Scenario | Method | λ / KS grid | ℓ (arcmin) / KS smoothing (pixels) |', '|---|---|---:|---:|']
    for name,cal in calibrations.items():
        for m,c in cal['calibrations'].items():
            a,b=c['parameters'];lines.append(f'| {name} | {m} | {a:.6g} | {b:.6g} |')
    lines += ['', '## Paired baseline differences', '',
        'Difference = second method error − first method error; positive favours the first. '
        'Intervals are Student-t 95% intervals across six paired catalogues. Sign-test p values '
        'are exact and two-sided, with no correction for the many exploratory comparisons. '
        'No t statistic is described as Gaussian “sigma”.','',
        '| Density | First − second (error improvement) | Mean | SE | 95% interval | Wins | Sign p |',
        '|---:|---|---:|---:|---|---:|---:|']
    for p in pairs:
        if not p['scenario'].startswith('density-'):continue
        lo,hi=p['ci95'];lines.append(f"| {p['n_eff_nominal']:g} | {p['method_a']} − {p['method_b']} | {p['mean_diff']:.4f} | {p['se_diff']:.4f} | [{lo:.4f}, {hi:.4f}] | {p['wins']}/{p['n_pairs']} | {p['sign_p']:.4f} |")
    lines += ['', '## Scope experiments', '',
        'Each scenario is recalibrated independently using the same protocol, with evaluation seeds held out. '
        'Unspecified settings equal the baseline at count density 10. Radius experiments hold count density at 5. '
        'Weighted density uses (Σw)²/Σw² per gross area; masks preserve the source count and increase accessible-area density.','',
        '| Scenario | P3 | Argyris | HCT | KS |', '|---|---:|---:|---:|---:|']
    for config in configs:
        name=config['name']
        if name.startswith('density-'):continue
        rs={r['method']:r for r in avg if r['scenario']==name}
        lines.append('| '+name+' | '+' | '.join(f"{rs[m]['shape_l2']:.4f} ± {rs[m]['shape_l2_std']:.4f}" for m in METHODS)+' |')
    lines += ['', '## Integrity audit', '',
        f"{len(allrows)} held-out method/catalogue evaluations; {sum(r['failed_evaluations'] for r in audit)} failed. "
        f"{sum(r['failed_candidates'] for r in audit)} failed parameter candidates; "
        f"{sum(r['boundary_unresolved'] for r in audit)} unresolved search edges.", '',
        'Full candidate rows, expansions, final parameters, source catalogues, per-seed maps, '
        'and numerical residuals are retained beside this report. Failed candidates or unresolved edges '
        'must be resolved or disclosed before quoting a ranking. Finite grids cannot prove a global optimum. '
        'Timing was collected under concurrent benchmark load and is not a dedicated performance claim.', '',
        '![Density and noise comparison](calibration.png)', '']
    result_text='\n'.join(lines)
    (out/'RESULTS.md').write_text(result_text)
    if update_math:
        path=Path(__file__).resolve().parents[2]/'MATH.md'
        text=path.read_text();start='<!-- CALIBRATED_BASELINE_START -->';end='<!-- CALIBRATED_BASELINE_END -->'
        if text.count(start)!=1 or text.count(end)!=1:raise ValueError('MATH table markers missing or ambiguous')
        table=result_text.split('## Density baseline')[1].split('## Frozen settings')[0].strip()
        a=text.index(start)+len(start);b=text.index(end)
        path.write_text(text[:a]+'\n\n'+table+'\n\n'+text[b:])
    import matplotlib
    matplotlib.use('Agg')
    import matplotlib.pyplot as plt
    fig,axes=plt.subplots(1,2,figsize=(10,4),layout='constrained')
    for ax,names,x,label in [(axes[0],[f'density-{n}' for n in (5,10,20,30)],[5,10,20,30],'Count density [arcmin⁻²]'),
                              (axes[1],['density-10','noise-0.1','noise-0.2','noise-0.3'],[.05,.1,.2,.3],'Shear noise per component')]:
        for m in METHODS:
            rs=[next(r for r in avg if r['scenario']==name and r['method']==m) for name in names]
            ax.errorbar(x,[r['shape_l2'] for r in rs],yerr=[r['shape_l2_std'] for r in rs],marker='o',capsize=3,label=m)
        ax.set_xlabel(label);ax.set_ylabel('DC-removed relative L2');ax.grid(alpha=.2)
    axes[0].set_title('Radius 3′, noise 0.05');axes[1].set_title('Radius 3′, density 10 arcmin⁻²')
    axes[1].legend();fig.savefig(out/'calibration.png',dpi=180);plt.close(fig)
    return audit

if __name__=='__main__':
    p=argparse.ArgumentParser();p.add_argument('--root',default='benchmarks/calibration/runs');p.add_argument('--output',default='benchmarks/calibration')
    p.add_argument('--update-math',action='store_true',help='replace the marked baseline table in MATH.md')
    a=p.parse_args();report(a.root,a.output,a.update_math)
